/* eslint-disable @typescript-eslint/no-explicit-any -- mirrors SpiceApp state that is typed `any` there. */
/**
 * View-model contract between the SpiceApp controller (spice-app.tsx) and the
 * preview "UI v2" component tree.
 *
 * SpiceApp owns every piece of state, effect, and handler; UI v2 is purely
 * presentational and reads everything through `useSpiceUi()`. The model
 * exposes every top-level SpiceApp declaration (minus the shared <audio>
 * plumbing and classic-only renderers) plus the module helpers the classic
 * interface renders with, so both interfaces drive identical behavior.
 *
 * Generated from the TypeScript checker; when SpiceApp gains a declaration
 * that UI v2 needs, add the field here and to the `uiModel` object literal.
 */
import type { Dispatch, ReactNode, RefObject, SetStateAction } from 'react';
import type { ProfileListenDeliveryState, ProfileListenProvider, ProfileListenType } from '../../lib/profile-listen-delivery';
import type { ReleaseNotification } from '../../lib/release-notifications';
import type { SpiceConnectHandoffDestinationState } from '../../lib/spice-connect-handoff';
import type { SpiceConnectLanDeviceState, SpiceConnectLanTransport } from '../../lib/spice-connect-lan';
import type { ThemePalette } from '../../lib/theme-palette';
import type { AdaptiveTrackPriorityState } from '../adaptive-track-priority';
import type { CommandPaletteCommand } from '../command-palette';
import type { HomeHistoryShelves } from '../home-history';
import type { ListeningTimeProfile } from '../listening-context';
import type { ListeningEvent, WeeklyListeningRecap } from '../listening-insights';
import type { PlaybackProfile, PlaybackProfileState } from '../playback-profiles';
import type { RecommendationPreferences } from '../recommendation-preferences';
import type { RecommendationListenProgress, RecommendationSeed, RecommendationShelf, TasteProfile } from '../recommendations';
import type { PairedDeviceAuthorization, PairingCodeResult } from '../secure-pairing-panel';
import type { ShuffleHistoryState } from '../shuffle-history';
import type { AccentTheme, AccountBlockState, AppPage, ArtworkShape, CloudAccount, DesktopOfflineLibraryEntry, DesktopStartOnBootPreference, InterfaceScale, LyricLine, MotionLevel, NativeShellPreferences, NativeShellUpdateStatus, NativeToolbarButtonKey, OptimisticRemoteDeviceState, PendingInvite, PendingSpiceConnectHandoff, PlayerBarDensity, PlayerVisualStyle, Playlist, PlaylistInvitePreview, PlaylistMember, PreparedCrossfade, ProfileSyncProviderResult, ProfileSyncStatus, ReceiverSelectVariant, RemoteCommand, RemoteCommandType, RemoteDevice, SearchProvider, SongShareDialog, SpiceApiLane, SpiceConfirmDialog, SpiceConnectTransportDiagnostic, SpiceDesktopOfflineLibraryBridge, SpiceDesktopUpdaterBridge, SpiceNativeShellBridge, SpiceNotice, SpiceNoticeKind, StoredRemotePairingCredential, StreamProtocol, SyncOutboxPayload, TopbarLayout, TopbarSearchMode, Track, UserProfile, VisualSurface } from '../spice-app';
import type { SearchCacheEntry, TrackSnapshot } from '../spice-storage';
import type { DurableSyncOutbox, SyncOutboxItem } from '../sync-outbox';

export interface SpiceUiModel {
  SPICE_CONNECT_TRANSPORT_DIAGNOSTICS_STORAGE_KEY: string;
  MAX_LOCAL_PROFILES: number;
  SPICE_MEDIA_CORE_LABEL: string;
  spiceApiUrl: (lane: SpiceApiLane, path: string, query?: URLSearchParams | Record<string, string | number | boolean | null | undefined>) => string;
  NATIVE_TOOLBAR_CONTROLS: { id: NativeToolbarButtonKey; label: string; description: string; }[];
  getSpiceNativeShellBridge: () => SpiceNativeShellBridge | null;
  getSpiceDesktopUpdaterBridge: () => SpiceDesktopUpdaterBridge | null;
  getSpiceDesktopOfflineLibraryBridge: () => SpiceDesktopOfflineLibraryBridge | null;
  formatOfflineLibrarySize: (bytes: number) => string;
  nativeUpdateStatusMessage: (status: NativeShellUpdateStatus | null) => string;
  SEARCH_PROVIDER_LABELS: Record<SearchProvider, string>;
  TOPBAR_SEARCH_MODE_LABELS: Record<TopbarSearchMode, string>;
  VISUAL_SURFACE_LABELS: Record<VisualSurface, string>;
  ARTWORK_SHAPE_LABELS: Record<ArtworkShape, string>;
  MOTION_LEVEL_LABELS: Record<MotionLevel, string>;
  INTERFACE_SCALE_LABELS: Record<InterfaceScale, string>;
  TOPBAR_LAYOUT_LABELS: Record<TopbarLayout, string>;
  PLAYER_BAR_DENSITY_LABELS: Record<PlayerBarDensity, string>;
  PLAYER_VISUAL_STYLE_LABELS: Record<PlayerVisualStyle, string>;
  PROFILE_SYNC_STATUS_LABELS: Record<ProfileSyncStatus, string>;
  trackListFingerprint: (tracks: Track[]) => string;
  PRESET_GRADIENTS: string[];
  PRESET_AVATARS: { name: string; url: string; }[];
  genres: { name: string; gradient: string; icon: ReactNode; }[];
  formatTime: (seconds: number) => string;
  trackSourceLabel: (track: Track) => 'Offline Library' | 'SoundCloud' | 'YouTube Video' | 'YouTube Music';
  isSearchProvider: (value: string | null) => value is SearchProvider;
  isStreamProtocol: (value: string | null) => value is StreamProtocol;
  isVisualSurface: (value: string | null) => value is VisualSurface;
  isArtworkShape: (value: string | null) => value is ArtworkShape;
  isMotionLevel: (value: string | null) => value is MotionLevel;
  isInterfaceScale: (value: string | null) => value is InterfaceScale;
  isTopbarLayout: (value: string | null) => value is TopbarLayout;
  isPlayerBarDensity: (value: string | null) => value is PlayerBarDensity;
  isPlayerVisualStyle: (value: string | null) => value is PlayerVisualStyle;
  playbackTrackKey: (track: Track) => string;
  profileArtistName: (track: Track) => string;
  profileOriginUrl: (track: Track) => string | undefined;
  isPlaylistUuid: (id: string) => boolean;
  volumeBoosterAccepted: boolean;
  setVolumeBoosterAccepted: Dispatch<SetStateAction<boolean>>;
  isVolumeHovered: boolean;
  setIsVolumeHovered: Dispatch<SetStateAction<boolean>>;
  currentPage: AppPage;
  setCurrentPage: Dispatch<SetStateAction<AppPage>>;
  selectedPlaylist: Playlist | null;
  setSelectedPlaylist: Dispatch<SetStateAction<Playlist | null>>;
  debugLogs: string[];
  setDebugLogs: Dispatch<SetStateAction<string[]>>;
  logDebug: (category: string, message: string) => void;
  accentTheme: AccentTheme;
  setAccentTheme: Dispatch<SetStateAction<AccentTheme>>;
  customThemePalette: ThemePalette;
  setCustomThemePalette: Dispatch<SetStateAction<ThemePalette>>;
  customThemeEnabled: boolean;
  setCustomThemeEnabled: Dispatch<SetStateAction<boolean>>;
  visualSurface: VisualSurface;
  setVisualSurface: Dispatch<SetStateAction<VisualSurface>>;
  artworkShape: ArtworkShape;
  setArtworkShape: Dispatch<SetStateAction<ArtworkShape>>;
  motionLevel: MotionLevel;
  setMotionLevel: Dispatch<SetStateAction<MotionLevel>>;
  interfaceScale: InterfaceScale;
  setInterfaceScale: Dispatch<SetStateAction<InterfaceScale>>;
  topbarLayout: TopbarLayout;
  setTopbarLayout: Dispatch<SetStateAction<TopbarLayout>>;
  audioQuality: 'standard' | 'high' | 'low';
  setAudioQuality: Dispatch<SetStateAction<'standard' | 'high' | 'low'>>;
  streamProtocol: StreamProtocol;
  setStreamProtocol: Dispatch<SetStateAction<StreamProtocol>>;
  playbackProfileState: PlaybackProfileState;
  setPlaybackProfileState: Dispatch<SetStateAction<PlaybackProfileState>>;
  activePlaybackProfile: PlaybackProfile;
  sidebarHidden: boolean;
  setSidebarHidden: Dispatch<SetStateAction<boolean>>;
  sidebarSearchEnabled: boolean;
  setSidebarSearchEnabled: Dispatch<SetStateAction<boolean>>;
  sidebarProfileEnabled: boolean;
  setSidebarProfileEnabled: Dispatch<SetStateAction<boolean>>;
  sidebarSettingsEnabled: boolean;
  setSidebarSettingsEnabled: Dispatch<SetStateAction<boolean>>;
  desktopUpdaterAvailable: boolean;
  setDesktopUpdaterAvailable: Dispatch<SetStateAction<boolean>>;
  desktopStartOnBoot: DesktopStartOnBootPreference | null;
  setDesktopStartOnBoot: Dispatch<SetStateAction<DesktopStartOnBootPreference | null>>;
  desktopStartOnBootMessage: string | null;
  setDesktopStartOnBootMessage: Dispatch<SetStateAction<string | null>>;
  nativeShellAvailable: boolean;
  setNativeShellAvailable: Dispatch<SetStateAction<boolean>>;
  nativeShellSettings: NativeShellPreferences | null;
  setNativeShellSettings: Dispatch<SetStateAction<NativeShellPreferences | null>>;
  nativeShellCssDraft: string;
  setNativeShellCssDraft: Dispatch<SetStateAction<string>>;
  nativeShellMessage: string | null;
  setNativeShellMessage: Dispatch<SetStateAction<string | null>>;
  nativeShellBusy: string | null;
  setNativeShellBusy: Dispatch<SetStateAction<string | null>>;
  nativeUpdateStatus: NativeShellUpdateStatus | null;
  setNativeUpdateStatus: Dispatch<SetStateAction<NativeShellUpdateStatus | null>>;
  profileSyncEnabled: boolean;
  setProfileSyncEnabled: Dispatch<SetStateAction<boolean>>;
  lastFmSessionKey: string;
  setLastFmSessionKey: Dispatch<SetStateAction<string>>;
  lastFmAccountLinked: boolean;
  setLastFmAccountLinked: Dispatch<SetStateAction<boolean>>;
  lastFmLinkedUser: string;
  setLastFmLinkedUser: Dispatch<SetStateAction<string>>;
  lastFmLinkStatus: string | null;
  setLastFmLinkStatus: Dispatch<SetStateAction<string | null>>;
  lastFmPlaybackStatus: string | null;
  setLastFmPlaybackStatus: Dispatch<SetStateAction<string | null>>;
  isLinkingLastFm: boolean;
  setIsLinkingLastFm: Dispatch<SetStateAction<boolean>>;
  listenBrainzToken: string;
  setListenBrainzToken: Dispatch<SetStateAction<string>>;
  listenBrainzAccountLinked: boolean;
  setListenBrainzAccountLinked: Dispatch<SetStateAction<boolean>>;
  listenBrainzLinkStatus: string | null;
  setListenBrainzLinkStatus: Dispatch<SetStateAction<string | null>>;
  listenBrainzSaveTimeoutRef: RefObject<NodeJS.Timeout | null>;
  migratedLegacyListenBrainzRef: RefObject<boolean>;
  profileSyncStatus: ProfileSyncStatus;
  setProfileSyncStatus: Dispatch<SetStateAction<ProfileSyncStatus>>;
  showQueueDrawer: boolean;
  setShowQueueDrawer: Dispatch<SetStateAction<boolean>>;
  commandPaletteOpen: boolean;
  setCommandPaletteOpen: Dispatch<SetStateAction<boolean>>;
  spiceNotices: SpiceNotice[];
  setSpiceNotices: Dispatch<SetStateAction<SpiceNotice[]>>;
  spiceConfirm: SpiceConfirmDialog | null;
  setSpiceConfirm: Dispatch<SetStateAction<SpiceConfirmDialog | null>>;
  songShareDialog: SongShareDialog | null;
  setSongShareDialog: Dispatch<SetStateAction<SongShareDialog | null>>;
  offlineLibraryEntries: DesktopOfflineLibraryEntry[];
  setOfflineLibraryEntries: Dispatch<SetStateAction<DesktopOfflineLibraryEntry[]>>;
  offlineLibraryDirectory: string;
  setOfflineLibraryDirectory: Dispatch<SetStateAction<string>>;
  offlineLibraryBridgeState: 'checking' | 'available' | 'error' | 'unavailable';
  setOfflineLibraryBridgeState: Dispatch<SetStateAction<'checking' | 'available' | 'error' | 'unavailable'>>;
  offlineLibraryTotalBytes: number;
  offlineDownloadTrackId: string | null;
  setOfflineDownloadTrackId: Dispatch<SetStateAction<string | null>>;
  offlineDownloadTrackIdRef: RefObject<string | null>;
  playlistDownloadProgress: { playlistId: string; completed: number; total: number; } | null;
  setPlaylistDownloadProgress: Dispatch<SetStateAction<{ playlistId: string; completed: number; total: number; } | null>>;
  playlistDownloadCancelledRef: RefObject<boolean>;
  desktopMediaRuntimeReadyRef: RefObject<boolean>;
  activeNoticeTimersRef: RefObject<Map<number, NodeJS.Timeout>>;
  activePlaybackProfileRef: RefObject<PlaybackProfile>;
  dismissSpiceNotice: (id: number) => void;
  showSpiceNotice: (message: string, kind?: SpiceNoticeKind) => void;
  copyTextToClipboard: (text: string) => Promise<boolean>;
  shareSongLink: (track: Track, event?: React.MouseEvent<HTMLElement>) => void;
  copySongShareLink: () => Promise<void>;
  refreshOfflineLibrary: () => Promise<boolean>;
  fetchTrackDownloadBlob: (track: Track) => Promise<Blob>;
  saveTrackDownload: (track: Track) => Promise<void>;
  downloadTrackToOfflineLibrary: (track: Track, quiet?: boolean) => Promise<void>;
  downloadSharedSong: () => Promise<void>;
  openSongSource: () => void;
  requestSpiceConfirm: (dialog: SpiceConfirmDialog) => void;
  cancelSpiceConfirm: () => void;
  feedbackCategory: string;
  setFeedbackCategory: Dispatch<SetStateAction<string>>;
  feedbackRating: number;
  setFeedbackRating: Dispatch<SetStateAction<number>>;
  feedbackText: string;
  setFeedbackText: Dispatch<SetStateAction<string>>;
  isSubmittingFeedback: boolean;
  setIsSubmittingFeedback: Dispatch<SetStateAction<boolean>>;
  feedbackStatus: string;
  setFeedbackStatus: Dispatch<SetStateAction<string>>;
  playedTracksCount: number;
  setPlayedTracksCount: Dispatch<SetStateAction<number>>;
  showFeedbackPopup: boolean;
  setShowFeedbackPopup: Dispatch<SetStateAction<boolean>>;
  profiles: UserProfile[];
  setProfiles: Dispatch<SetStateAction<UserProfile[]>>;
  activeProfileId: string;
  setActiveProfileId: Dispatch<SetStateAction<string>>;
  isProfileHydrated: boolean;
  setIsProfileHydrated: Dispatch<SetStateAction<boolean>>;
  activeSettingsSection: string;
  setActiveSettingsSection: Dispatch<SetStateAction<string>>;
  activeProfile: UserProfile;
  recommendationPreferences: RecommendationPreferences;
  setRecommendationPreferences: Dispatch<SetStateAction<RecommendationPreferences>>;
  listeningEvents: ListeningEvent[];
  setListeningEvents: Dispatch<SetStateAction<ListeningEvent[]>>;
  adaptiveTrackPriorityRef: RefObject<AdaptiveTrackPriorityState>;
  adaptiveTasteScores: Record<string, number>;
  setAdaptiveTasteScores: Dispatch<SetStateAction<Record<string, number>>>;
  listenersLikeYou: { tracks: Track[]; neighborCount: number; } | null;
  setListenersLikeYou: Dispatch<SetStateAction<{ tracks: Track[]; neighborCount: number; } | null>>;
  collaborativeTasteScores: Record<string, number>;
  setCollaborativeTasteScores: Dispatch<SetStateAction<Record<string, number>>>;
  adaptiveListenCycleRef: RefObject<{ trackKey: string; completionDisqualified: boolean; } | null>;
  adaptivePlaybackStartedRef: RefObject<(track: Track) => void>;
  syncOutboxItems: SyncOutboxItem<SyncOutboxPayload>[];
  setSyncOutboxItems: Dispatch<SetStateAction<SyncOutboxItem<SyncOutboxPayload>[]>>;
  weeklyListeningRecap: WeeklyListeningRecap;
  isLocked: boolean;
  setIsLocked: Dispatch<SetStateAction<boolean>>;
  passcodeInput: string;
  setPasscodeInput: Dispatch<SetStateAction<string>>;
  passcodeError: string | null;
  setPasscodeError: Dispatch<SetStateAction<string | null>>;
  showCreateProfileDialog: boolean;
  setShowCreateProfileDialog: Dispatch<SetStateAction<boolean>>;
  newProfileName: string;
  setNewProfileName: Dispatch<SetStateAction<string>>;
  newProfileBio: string;
  setNewProfileBio: Dispatch<SetStateAction<string>>;
  newProfileGradient: string;
  setNewProfileGradient: Dispatch<SetStateAction<string>>;
  newProfilePasscode: string;
  setNewProfilePasscode: Dispatch<SetStateAction<string>>;
  newProfileAvatarUrl: string;
  setNewProfileAvatarUrl: Dispatch<SetStateAction<string>>;
  currentTrack: Track;
  setCurrentTrack: Dispatch<SetStateAction<Track>>;
  streamUrl: string | null;
  setStreamUrl: Dispatch<SetStateAction<string | null>>;
  isPlaying: boolean;
  setIsPlaying: Dispatch<SetStateAction<boolean>>;
  isLoadingStream: boolean;
  setIsLoadingStream: Dispatch<SetStateAction<boolean>>;
  progress: number;
  setProgress: Dispatch<SetStateAction<number>>;
  duration: number;
  setDuration: Dispatch<SetStateAction<number>>;
  remotePlaybackClock: number;
  setRemotePlaybackClock: Dispatch<SetStateAction<number>>;
  volume: number;
  setVolume: Dispatch<SetStateAction<number>>;
  likedTracks: Set<string>;
  setLikedTracks: Dispatch<SetStateAction<Set<string>>>;
  likedTrackDetails: Record<string, Track>;
  setLikedTrackDetails: Dispatch<SetStateAction<Record<string, Track>>>;
  customPlaylists: Playlist[];
  setCustomPlaylists: Dispatch<SetStateAction<Playlist[]>>;
  likedTracksRef: RefObject<Set<string>>;
  likedTrackDetailsRef: RefObject<Record<string, Track>>;
  customPlaylistsRef: RefObject<Playlist[]>;
  history: Track[];
  setHistory: Dispatch<SetStateAction<Track[]>>;
  queue: Track[];
  setQueue: Dispatch<SetStateAction<Track[]>>;
  queueIndex: number;
  setQueueIndex: Dispatch<SetStateAction<number>>;
  homeHistoryShelves: HomeHistoryShelves<Track>;
  privateTasteProfile: TasteProfile;
  tasteAffinityContext: { profile: TasteProfile; preferences: RecommendationPreferences; adaptiveScores: Record<string, number>; likedTrackKeys: Set<string>; recentTrackKeys: Set<string>; collaborativeScores: Record<string, number>; };
  libraryView: 'grid' | 'list';
  setLibraryView: Dispatch<SetStateAction<'grid' | 'list'>>;
  libraryFilter: 'shared' | 'playlists' | 'liked' | 'history' | 'downloads';
  setLibraryFilter: Dispatch<SetStateAction<'shared' | 'playlists' | 'liked' | 'history' | 'downloads'>>;
  editName: string;
  setEditName: Dispatch<SetStateAction<string>>;
  editBio: string;
  setEditBio: Dispatch<SetStateAction<string>>;
  editGradient: string;
  setEditGradient: Dispatch<SetStateAction<string>>;
  editPasscode: string;
  setEditPasscode: Dispatch<SetStateAction<string>>;
  editAvatarUrl: string;
  setEditAvatarUrl: Dispatch<SetStateAction<string>>;
  isEditingProfile: boolean;
  setIsEditingProfile: Dispatch<SetStateAction<boolean>>;
  ytPlaylistLink: string;
  setYtPlaylistLink: Dispatch<SetStateAction<string>>;
  isImportingPlaylist: boolean;
  setIsImportingPlaylist: Dispatch<SetStateAction<boolean>>;
  playlistImportError: string | null;
  setPlaylistImportError: Dispatch<SetStateAction<string | null>>;
  playlistImportSuccess: string | null;
  setPlaylistImportSuccess: Dispatch<SetStateAction<string | null>>;
  jsonImportText: string;
  setJsonImportText: Dispatch<SetStateAction<string>>;
  _jsonBackupStatus: 'success' | 'error' | null;
  setJsonBackupStatus: Dispatch<SetStateAction<'success' | 'error' | null>>;
  showCreateDialog: boolean;
  setShowCreateDialog: Dispatch<SetStateAction<boolean>>;
  newPlTitle: string;
  setNewPlTitle: Dispatch<SetStateAction<string>>;
  newPlDesc: string;
  setNewPlDesc: Dispatch<SetStateAction<string>>;
  playlistPickerTrack: Track | null;
  setPlaylistPickerTrack: Dispatch<SetStateAction<Track | null>>;
  playlistPickerSavingId: string | null;
  setPlaylistPickerSavingId: Dispatch<SetStateAction<string | null>>;
  newPlaylistSeedTrack: Track | null;
  setNewPlaylistSeedTrack: Dispatch<SetStateAction<Track | null>>;
  showEditPlaylistDialog: boolean;
  setShowEditPlaylistDialog: Dispatch<SetStateAction<boolean>>;
  editPlTitle: string;
  setEditPlTitle: Dispatch<SetStateAction<string>>;
  editPlDesc: string;
  setEditPlDesc: Dispatch<SetStateAction<string>>;
  editPlGradient: string;
  setEditPlGradient: Dispatch<SetStateAction<string>>;
  editPlCoverUrl: string;
  setEditPlCoverUrl: Dispatch<SetStateAction<string>>;
  newPlIsPublic: boolean;
  setNewPlIsPublic: Dispatch<SetStateAction<boolean>>;
  editPlIsPublic: boolean;
  setEditPlIsPublic: Dispatch<SetStateAction<boolean>>;
  searchTab: 'users' | 'tracks';
  setSearchTab: Dispatch<SetStateAction<'users' | 'tracks'>>;
  searchForYouOnly: boolean;
  setSearchForYouOnly: Dispatch<SetStateAction<boolean>>;
  userSearchQuery: string;
  setUserSearchQuery: Dispatch<SetStateAction<string>>;
  userSearchResults: any[];
  setUserSearchResults: Dispatch<SetStateAction<any[]>>;
  isSearchingUsers: boolean;
  setIsSearchingUsers: Dispatch<SetStateAction<boolean>>;
  selectedUser: any;
  setSelectedUser: Dispatch<any>;
  selectedUserProfileData: any;
  setSelectedUserProfileData: Dispatch<any>;
  myLikesCount: number;
  setMyLikesCount: Dispatch<SetStateAction<number>>;
  isLoadingUserProfile: boolean;
  setIsLoadingUserProfile: Dispatch<SetStateAction<boolean>>;
  showDeleteConfirm: boolean;
  setShowDeleteConfirm: Dispatch<SetStateAction<boolean>>;
  listenTogetherSession: { id: string; } | null;
  setListenTogetherSession: Dispatch<SetStateAction<{ id: string; } | null>>;
  listenTogetherHostSessionId: string | null;
  setListenTogetherHostSessionId: Dispatch<SetStateAction<string | null>>;
  listenTogetherHostName: string | null;
  setListenTogetherHostName: Dispatch<SetStateAction<string | null>>;
  pendingListenInvites: any[];
  setPendingListenInvites: Dispatch<SetStateAction<any[]>>;
  listenTogetherDialogOpen: boolean;
  setListenTogetherDialogOpen: Dispatch<SetStateAction<boolean>>;
  listenTogetherInviteUsername: string;
  setListenTogetherInviteUsername: Dispatch<SetStateAction<string>>;
  listenTogetherJoinSessionId: string;
  setListenTogetherJoinSessionId: Dispatch<SetStateAction<string>>;
  listenTogetherInvitesList: any[];
  setListenTogetherInvitesList: Dispatch<SetStateAction<any[]>>;
  isSendingListenTogetherInvite: boolean;
  setIsSendingListenTogetherInvite: Dispatch<SetStateAction<boolean>>;
  listenTogetherStatus: string;
  setListenTogetherStatus: Dispatch<SetStateAction<string>>;
  isCreatingListenTogetherSession: boolean;
  setIsCreatingListenTogetherSession: Dispatch<SetStateAction<boolean>>;
  sharingPlaylistId: string | null;
  setSharingPlaylistId: Dispatch<SetStateAction<string | null>>;
  shareStatus: string | null;
  setShareStatus: Dispatch<SetStateAction<string | null>>;
  invitePreview: PlaylistInvitePreview | null;
  setInvitePreview: Dispatch<SetStateAction<PlaylistInvitePreview | null>>;
  inviteStatus: string | null;
  setInviteStatus: Dispatch<SetStateAction<string | null>>;
  acceptingInvite: boolean;
  setAcceptingInvite: Dispatch<SetStateAction<boolean>>;
  cloudUsername: string | null;
  setCloudUsername: Dispatch<SetStateAction<string | null>>;
  editUsername: string;
  setEditUsername: Dispatch<SetStateAction<string>>;
  usernameError: string | null;
  setUsernameError: Dispatch<SetStateAction<string | null>>;
  pendingInvites: PendingInvite[];
  setPendingInvites: Dispatch<SetStateAction<PendingInvite[]>>;
  pendingInvitesLoading: boolean;
  setPendingInvitesLoading: Dispatch<SetStateAction<boolean>>;
  notificationTrayOpen: boolean;
  setNotificationTrayOpen: Dispatch<SetStateAction<boolean>>;
  profileMenuOpen: boolean;
  setProfileMenuOpen: Dispatch<SetStateAction<boolean>>;
  selectedReleaseNotification: ReleaseNotification | null;
  setSelectedReleaseNotification: Dispatch<SetStateAction<ReleaseNotification | null>>;
  readReleaseNotificationIds: string[];
  setReadReleaseNotificationIds: Dispatch<SetStateAction<string[]>>;
  releaseNotifications: ReleaseNotification[];
  setReleaseNotifications: Dispatch<SetStateAction<ReleaseNotification[]>>;
  showMembersPanel: boolean;
  setShowMembersPanel: Dispatch<SetStateAction<boolean>>;
  membersLoading: boolean;
  setMembersLoading: Dispatch<SetStateAction<boolean>>;
  membersList: { owner: PlaylistMember; members: PlaylistMember[]; maxMembers: number; } | null;
  setMembersList: Dispatch<SetStateAction<{ owner: PlaylistMember; members: PlaylistMember[]; maxMembers: number; } | null>>;
  inviteUsername: string;
  setInviteUsername: Dispatch<SetStateAction<string>>;
  invitingMember: boolean;
  setInvitingMember: Dispatch<SetStateAction<boolean>>;
  memberActionStatus: string | null;
  setMemberActionStatus: Dispatch<SetStateAction<string | null>>;
  showCreateSharedDialog: boolean;
  setShowCreateSharedDialog: Dispatch<SetStateAction<boolean>>;
  newSharedPlTitle: string;
  setNewSharedPlTitle: Dispatch<SetStateAction<string>>;
  newSharedPlDesc: string;
  setNewSharedPlDesc: Dispatch<SetStateAction<string>>;
  cloudToken: string | null;
  setCloudToken: Dispatch<SetStateAction<string | null>>;
  pairedRemoteCredential: StoredRemotePairingCredential | null;
  setPairedRemoteCredential: Dispatch<SetStateAction<StoredRemotePairingCredential | null>>;
  cloudUser: CloudAccount | null;
  setCloudUser: Dispatch<SetStateAction<CloudAccount | null>>;
  syncingStatus: 'success' | 'idle' | 'error' | 'syncing' | 'partial' | null;
  setSyncingStatus: Dispatch<SetStateAction<'success' | 'idle' | 'error' | 'syncing' | 'partial' | null>>;
  dbError: string | null;
  setDbError: Dispatch<SetStateAction<string | null>>;
  accountBlock: AccountBlockState | null;
  setAccountBlock: Dispatch<SetStateAction<AccountBlockState | null>>;
  isLocalDbFallback: boolean;
  setIsLocalDbFallback: Dispatch<SetStateAction<boolean>>;
  remoteControlEnabled: boolean;
  setRemoteControlEnabled: Dispatch<SetStateAction<boolean>>;
  remoteRealtimeConnected: boolean;
  setRemoteRealtimeConnected: Dispatch<SetStateAction<boolean>>;
  remoteDeviceId: string;
  activePairedRemoteCredential: StoredRemotePairingCredential | null;
  remoteAuthToken: string | null;
  remoteDeviceName: string;
  setRemoteDeviceName: Dispatch<SetStateAction<string>>;
  remoteDevices: RemoteDevice[];
  setRemoteDevices: Dispatch<SetStateAction<RemoteDevice[]>>;
  selectedRemoteDeviceId: string;
  setSelectedRemoteDeviceId: Dispatch<SetStateAction<string>>;
  incomingRemoteControllerId: string;
  setIncomingRemoteControllerId: Dispatch<SetStateAction<string>>;
  remoteStatus: string | null;
  setRemoteStatus: Dispatch<SetStateAction<string | null>>;
  remoteTransport: 'unknown' | 'redis' | 'postgresql';
  setRemoteTransport: Dispatch<SetStateAction<'unknown' | 'redis' | 'postgresql'>>;
  remoteLanPeerDeviceIds: string[];
  setRemoteLanPeerDeviceIds: Dispatch<SetStateAction<string[]>>;
  remoteTransportDiagnosticsEnabled: boolean;
  setRemoteTransportDiagnosticsEnabled: Dispatch<SetStateAction<boolean>>;
  remoteTransportDiagnostic: SpiceConnectTransportDiagnostic | null;
  setRemoteTransportDiagnostic: Dispatch<SetStateAction<SpiceConnectTransportDiagnostic | null>>;
  remoteLanLatencyMsByDevice: Record<string, number>;
  setRemoteLanLatencyMsByDevice: Dispatch<SetStateAction<Record<string, number>>>;
  remoteRedisConfigured: boolean | null;
  setRemoteRedisConfigured: Dispatch<SetStateAction<boolean | null>>;
  forgettingRemoteDeviceIds: Set<string>;
  setForgettingRemoteDeviceIds: Dispatch<SetStateAction<Set<string>>>;
  receiverMenuOpen: ReceiverSelectVariant | null;
  setReceiverMenuOpen: Dispatch<SetStateAction<ReceiverSelectVariant | null>>;
  playerPlacement: 'bottom' | 'top';
  setPlayerPlacement: Dispatch<SetStateAction<'bottom' | 'top'>>;
  playerViewMode: 'bar' | 'expanded' | 'mini';
  setPlayerViewMode: Dispatch<SetStateAction<'bar' | 'expanded' | 'mini'>>;
  playerBarDensity: PlayerBarDensity;
  setPlayerBarDensity: Dispatch<SetStateAction<PlayerBarDensity>>;
  playerVisualStyle: PlayerVisualStyle;
  setPlayerVisualStyle: Dispatch<SetStateAction<PlayerVisualStyle>>;
  showVideoPlayer: boolean;
  setShowVideoPlayer: Dispatch<SetStateAction<boolean>>;
  miniPlayerPos: { x: number; y: number; } | null;
  setMiniPlayerPos: Dispatch<SetStateAction<{ x: number; y: number; } | null>>;
  isDraggingMini: boolean;
  setIsDraggingMini: Dispatch<SetStateAction<boolean>>;
  dragStartRef: RefObject<{ x: number; y: number; }>;
  isShuffle: boolean;
  setIsShuffle: Dispatch<SetStateAction<boolean>>;
  repeatMode: 'none' | 'all' | 'one';
  setRepeatMode: Dispatch<SetStateAction<'none' | 'all' | 'one'>>;
  expandedTab: 'lyrics' | 'queue' | 'controls';
  setExpandedTab: Dispatch<SetStateAction<'lyrics' | 'queue' | 'controls'>>;
  lyricsData: { lines: LyricLine[]; plainLyrics: string; syncedLyrics: string; isSynced: boolean; } | null;
  setLyricsData: Dispatch<SetStateAction<{ lines: LyricLine[]; plainLyrics: string; syncedLyrics: string; isSynced: boolean; } | null>>;
  lyricsLoading: boolean;
  setLyricsLoading: Dispatch<SetStateAction<boolean>>;
  isKaraokeMode: boolean;
  setIsKaraokeMode: Dispatch<SetStateAction<boolean>>;
  lyricsContainerRef: RefObject<HTMLDivElement | null>;
  showBarLyrics: boolean;
  setShowBarLyrics: Dispatch<SetStateAction<boolean>>;
  showMiniLyrics: boolean;
  setShowMiniLyrics: Dispatch<SetStateAction<boolean>>;
  showMiniQueue: boolean;
  setShowMiniQueue: Dispatch<SetStateAction<boolean>>;
  showSyncEmail: boolean;
  setShowSyncEmail: Dispatch<SetStateAction<boolean>>;
  lastUnlockedProfileIdRef: RefObject<string>;
  authEmail: string;
  setAuthEmail: Dispatch<SetStateAction<string>>;
  authPassword: string;
  setAuthPassword: Dispatch<SetStateAction<string>>;
  authUsername: string;
  setAuthUsername: Dispatch<SetStateAction<string>>;
  authMode: 'login' | 'register';
  setAuthMode: Dispatch<SetStateAction<'login' | 'register'>>;
  authError: string | null;
  setAuthError: Dispatch<SetStateAction<string | null>>;
  authLoading: boolean;
  setAuthLoading: Dispatch<SetStateAction<boolean>>;
  emailVerification: { registrationId: string; email: string; } | null;
  setEmailVerification: Dispatch<SetStateAction<{ registrationId: string; email: string; } | null>>;
  emailVerificationCode: string;
  setEmailVerificationCode: Dispatch<SetStateAction<string>>;
  authForgotMode: boolean;
  setAuthForgotMode: Dispatch<SetStateAction<boolean>>;
  authForgotSent: boolean;
  setAuthForgotSent: Dispatch<SetStateAction<boolean>>;
  homeTrending: Track[];
  setHomeTrending: Dispatch<SetStateAction<Track[]>>;
  homeRecommended: Track[];
  setHomeRecommended: Dispatch<SetStateAction<Track[]>>;
  homeRecommendationShelves: RecommendationShelf<Track>[];
  setHomeRecommendationShelves: Dispatch<SetStateAction<RecommendationShelf<Track>[]>>;
  homeBecauseShelf: { label: string; reason: string; tracks: Track[]; } | null;
  setHomeBecauseShelf: Dispatch<SetStateAction<{ label: string; reason: string; tracks: Track[]; } | null>>;
  homeFreshFinds: Track[];
  setHomeFreshFinds: Dispatch<SetStateAction<Track[]>>;
  homeTimeMix: { label: string; reason: string; tracks: Track[]; } | null;
  setHomeTimeMix: Dispatch<SetStateAction<{ label: string; reason: string; tracks: Track[]; } | null>>;
  listeningTimeProfile: ListeningTimeProfile;
  onRepeatShelf: { label: string; reason: string; tracks: Track[]; } | null;
  homeRecommendationSeed: RecommendationSeed | null;
  setHomeRecommendationSeed: Dispatch<SetStateAction<RecommendationSeed | null>>;
  isLoadingRecommendations: boolean;
  setIsLoadingRecommendations: Dispatch<SetStateAction<boolean>>;
  isLoadingHome: boolean;
  setIsLoadingHome: Dispatch<SetStateAction<boolean>>;
  searchQuery: string;
  setSearchQuery: Dispatch<SetStateAction<string>>;
  topbarSearchQuery: string;
  setTopbarSearchQuery: Dispatch<SetStateAction<string>>;
  searchProvider: SearchProvider;
  setSearchProvider: Dispatch<SetStateAction<SearchProvider>>;
  searchResults: Track[];
  setSearchResults: Dispatch<SetStateAction<Track[]>>;
  searchResultsSource: 'network' | 'cache' | null;
  setSearchResultsSource: Dispatch<SetStateAction<'network' | 'cache' | null>>;
  isSearching: boolean;
  setIsSearching: Dispatch<SetStateAction<boolean>>;
  topbarSearchTrayOpen: boolean;
  setTopbarSearchTrayOpen: Dispatch<SetStateAction<boolean>>;
  quickSearchTab: 'users' | 'tracks';
  setQuickSearchTab: Dispatch<SetStateAction<'users' | 'tracks'>>;
  topbarUserSearchResults: any[];
  setTopbarUserSearchResults: Dispatch<SetStateAction<any[]>>;
  isSearchingTopbarUsers: boolean;
  setIsSearchingTopbarUsers: Dispatch<SetStateAction<boolean>>;
  recentSearchEntries: SearchCacheEntry[];
  setRecentSearchEntries: Dispatch<SetStateAction<SearchCacheEntry[]>>;
  topbarSearchShellRef: RefObject<HTMLDivElement | null>;
  topbarProfileShellRef: RefObject<HTMLDivElement | null>;
  error: string | undefined;
  setError: Dispatch<SetStateAction<string | undefined>>;
  selfTestRunning: boolean;
  setSelfTestRunning: Dispatch<SetStateAction<boolean>>;
  selfTestResults: { api: 'passed' | 'failed' | null; db: 'passed' | 'failed' | 'disabled' | null; embed: 'passed' | 'failed' | null; latency: number | null; };
  setSelfTestResults: Dispatch<SetStateAction<{ api: 'passed' | 'failed' | null; db: 'passed' | 'failed' | 'disabled' | null; embed: 'passed' | 'failed' | null; latency: number | null; }>>;
  terminalFilter: string;
  setTerminalFilter: Dispatch<SetStateAction<string>>;
  terminalAutoScroll: boolean;
  setTerminalAutoScroll: Dispatch<SetStateAction<boolean>>;
  logsCopied: boolean;
  setLogsCopied: Dispatch<SetStateAction<boolean>>;
  terminalEndRef: RefObject<HTMLDivElement | null>;
  launchIntentHandledRef: RefObject<boolean>;
  applyLastFmSession: (sessionKey: string, linkedUser?: string, accountLinked?: boolean) => void;
  prevTerminalAutoScrollRef: RefObject<boolean>;
  runSelfTest: () => Promise<void>;
  audioRef: RefObject<HTMLAudioElement | null>;
  audioSlotRefs: RefObject<[HTMLAudioElement | null, HTMLAudioElement | null]>;
  activeAudioSlotRef: RefObject<0 | 1>;
  audioTransitionGainsRef: RefObject<WeakMap<HTMLAudioElement, number>>;
  preparedCrossfadeRef: RefObject<PreparedCrossfade | null>;
  crossfadePreparationIdRef: RefObject<number>;
  crossfadeAnimationFrameRef: RefObject<number | null>;
  crossfadeAnimationStarterRef: RefObject<() => void>;
  audioContextRef: RefObject<AudioContext | null>;
  gainNodeRef: RefObject<GainNode | null>;
  sourceNodeRef: RefObject<MediaElementAudioSourceNode | null>;
  ytPlayerRef: RefObject<any>;
  searchTimeoutRef: RefObject<NodeJS.Timeout | null>;
  searchRequestRef: RefObject<number>;
  recommendationRequestRef: RefObject<number>;
  queueIndexRef: RefObject<number>;
  queueRef: RefObject<Track[]>;
  repeatModeRef: RefObject<'none' | 'all' | 'one'>;
  streamProtocolRef: RefObject<StreamProtocol>;
  isShuffleRef: RefObject<boolean>;
  activeProfileRef: RefObject<UserProfile>;
  activeProfileIdRef: RefObject<string>;
  listenTogetherHostSessionIdRef: RefObject<string | null>;
  cloudTokenRef: RefObject<string | null>;
  cloudUserRef: RefObject<CloudAccount | null>;
  cloudUsernameRef: RefObject<string | null>;
  progressRef: RefObject<number>;
  currentTrackRef: RefObject<Track>;
  isPlayingRef: RefObject<boolean>;
  streamUrlRef: RefObject<string | null>;
  isLoadingStreamRef: RefObject<boolean>;
  durationRef: RefObject<number>;
  volumeRef: RefObject<number>;
  playbackRetryTimeoutRef: RefObject<NodeJS.Timeout | null>;
  playbackRetryCountsRef: RefObject<Map<string, number>>;
  playbackTelemetryRecordedRef: RefObject<Set<string>>;
  recommendationListenCreditedRef: RefObject<boolean>;
  recommendationListenProgressRef: RefObject<RecommendationListenProgress | null>;
  personalizedQueueContinuationSuppressedRef: RefObject<string | null>;
  playlistQueueOriginRef: RefObject<string | null>;
  shuffleHistoryRef: RefObject<ShuffleHistoryState | null>;
  relatedQueueInFlightRef: RefObject<Map<string, Promise<Track[]>>>;
  relatedQueueCacheRef: RefObject<Map<string, Track[]>>;
  syncOutboxRef: RefObject<DurableSyncOutbox<SyncOutboxPayload> | null>;
  playbackRequestRef: RefObject<number>;
  shouldAutoPlayRef: RefObject<boolean>;
  clientBootedAtRef: RefObject<number>;
  suppressRemotePlaybackUntilRef: RefObject<number>;
  directEmbedRetryRef: RefObject<Set<string>>;
  embedProxyRetryRef: RefObject<Set<string>>;
  proxyUnresolvableRef: RefObject<Set<string>>;
  playbackFallbackAttemptedRef: RefObject<Set<string>>;
  boostProtocolHandoffRef: RefObject<boolean>;
  boostResumeSecondsRef: RefObject<{ trackKey: string; seconds: number; } | null>;
  pendingProxyStartSecondsRef: RefObject<{ trackKey: string; seconds: number; } | null>;
  captureSameTrackResumeSeconds: (track: Track) => void;
  seekEmbedToPendingResume: (resumeKey: string, requestId: number) => void;
  syncLockRef: RefObject<boolean>;
  scrobbleStateRef: RefObject<ProfileListenDeliveryState | null>;
  profileListenRetryTimeoutsRef: RefObject<Set<NodeJS.Timeout>>;
  remoteDeviceReportInFlightRef: RefObject<boolean>;
  remoteDeviceReportQueuedRef: RefObject<boolean>;
  remoteDeviceLoadInFlightRef: RefObject<boolean>;
  remoteCommandPollInFlightRef: RefObject<boolean>;
  emptyRemoteCommandPollsRef: RefObject<number>;
  appliedRemoteCommandIdsRef: RefObject<Set<string>>;
  remoteStateSyncTimeoutRef: RefObject<number | null>;
  remoteTargetRefreshTimeoutRef: RefObject<number | null>;
  optimisticRemoteDeviceStateRef: RefObject<OptimisticRemoteDeviceState | null>;
  forgettingRemoteDeviceIdsRef: RefObject<Set<string>>;
  remoteDeviceListRevisionRef: RefObject<number>;
  remoteRequestGenerationRef: RefObject<number>;
  pendingSpiceConnectHandoffRef: RefObject<PendingSpiceConnectHandoff | null>;
  preparedSpiceConnectHandoffsRef: RefObject<Map<string, SpiceConnectHandoffDestinationState>>;
  remoteLanTransportRef: RefObject<SpiceConnectLanTransport | null>;
  applyRemoteCommandRef: RefObject<(command: RemoteCommand, now: number, transport?: 'cloud' | 'lan') => void>;
  handleRemoteLanStateRef: RefObject<(peerDeviceId: string, state: SpiceConnectLanDeviceState) => void>;
  sendRemoteCommandRef: RefObject<(command: RemoteCommandType, payload?: RemoteCommand['payload'], targetDeviceId?: string, quiet?: boolean) => Promise<boolean>>;
  addTrackToPlaylistRef: RefObject<(track: Track, playlistId: string, playlistTitle?: string) => Promise<boolean>>;
  remotePlaylistMutationChainRef: RefObject<Promise<void>>;
  handleAudioEndedRef: RefObject<(slot?: 0 | 1, audio?: HTMLAudioElement | null) => void>;
  handleAudioErrorRef: RefObject<() => void>;
  playTrackRef: RefObject<(track: Track, newQueue?: Track[], queueIndexHint?: number, isSyncLoopCall?: boolean, isRetryCall?: boolean, preserveCurrentListenCycle?: boolean, playlistQueueOriginId?: string) => Promise<void>>;
  handleNextRef: RefObject<(overrideIndex?: any) => void>;
  ensurePersonalizedUpNextRef: RefObject<(track: Track) => Promise<Track[]>>;
  recordTrackDiscoveryWinRef: RefObject<(track: Track) => void>;
  tasteSyncTimerRef: RefObject<NodeJS.Timeout | null>;
  tasteSyncMetaKey: (profileId: string) => string;
  tasteSyncDirtyKey: (profileId: string) => string;
  readTasteSyncJson: (key: string) => Record<string, number>;
  markTasteDirty: (kind: 'adaptive' | 'preferences' | 'events') => void;
  resolveTasteSyncToken: (profileId: string) => string | null;
  scheduleTasteCloudSync: (immediate?: boolean) => void;
  applyAudioElementVolume: (audio: HTMLAudioElement | null, nextVolume?: number, options?: { resumeAudioContext?: boolean; }) => void;
  bindAudioSlotRef: (slot: 0 | 1, node: HTMLAudioElement | null) => void;
  autoSyncProfiles: (updatedProfiles: UserProfile[]) => void;
  updateProfileData: (profileId: string, updates: Partial<UserProfile>) => void;
  updateActiveProfileData: (updates: Partial<UserProfile>) => void;
  autoSyncHistory: (updatedHistory: Track[], profileId?: string, profileToken?: string | null) => void;
  autoSyncPlaylists: (updatedPlaylists: Playlist[]) => void;
  autoSyncLikes: (updatedLikes: string[], updatedDetails: Record<string, Track>) => void;
  handleUserSearch: (query: string) => Promise<void>;
  handleSelectUser: (user: any) => Promise<void>;
  handleToggleProfileLike: (userId: string) => Promise<void>;
  restoreProfileConnections: (token?: string | null) => Promise<void>;
  saveListenBrainzToken: (rawToken: string) => Promise<void>;
  queueListenBrainzTokenSave: (token: string) => void;
  isMounted: boolean;
  setIsMounted: Dispatch<SetStateAction<boolean>>;
  uiV2Enabled: boolean;
  setUiV2Enabled: (enabled: boolean) => void;
  loadPlaylistInvite: (token: string) => Promise<void>;
  scrollToSettingsSection: (id: string) => void;
  updateNativeShellBoolean: (key: 'discordRpcEnabled' | 'alwaysOnTop', enabled: boolean) => Promise<void>;
  updateNativeToolbarControl: (key: NativeToolbarButtonKey, enabled: boolean) => void;
  saveNativeShellCss: () => void;
  clearNativeShellCss: () => void;
  copyNativeUtilityUrl: (url: string, label: string) => Promise<void>;
  checkDesktopUpdates: () => Promise<void>;
  updateDesktopStartOnBoot: (enabled: boolean) => Promise<void>;
  initializeYtPlayer: () => void;
  setAudioTransitionGain: (audio: HTMLAudioElement, gain: number) => void;
  cancelPreparedCrossfade: (restoreOutgoing?: boolean) => void;
  resolveCrossfadeStreamUrl: (track: Track) => Promise<string>;
  isIntentionalPlaylistQueue: () => boolean;
  adaptiveWeightsForQueue: (tracks: Track[]) => number[];
  beginAdaptiveListenCycle: (track: Track) => void;
  finishAdaptiveListenCycle: (completedNaturally: boolean) => void;
  nextCrossfadeTarget: () => { track: Track; queueIndex: number; shuffleHistory?: ShuffleHistoryState; } | null;
  prepareCrossfade: () => Promise<void>;
  startPreparedCrossfade: () => void;
  updateCrossfade: (audio: HTMLAudioElement, currentTime: number) => void;
  finalizePreparedCrossfade: () => boolean;
  syncWithCloud: (token?: string | null, profileId?: string, sessionOverride?: Partial<Pick<UserProfile, 'cloudUser' | 'cloudUsername'>>) => Promise<void>;
  finishCloudAuthentication: (data: any, authProfileId: string, sourceMode: 'login' | 'register') => Promise<void>;
  handleAuthSubmit: (e: React.FormEvent) => Promise<void>;
  handleForgotSubmit: (e: React.FormEvent) => Promise<void>;
  disconnectListenTogetherForIdentityChange: (token?: string | null) => void;
  handleLogout: () => void;
  currentTrackKey: string;
  activeProfileListenProviders: () => ProfileListenProvider[];
  setPlaybackPlaying: (nextPlaying: boolean) => void;
  beginProfileListenCycle: (track: Track) => void;
  clearPlaybackRetryTimer: () => void;
  schedulePlaybackRetry: (track: Track, retryQueue: Track[], reason: string) => boolean;
  recordPlaybackTelemetry: (track: Track) => void;
  submitProfileListen: (type: ProfileListenType, listenedAt: number, providers: ProfileListenProvider[], track: Track, durationSeconds: number) => Promise<Partial<Record<ProfileListenProvider, ProfileSyncProviderResult>>>;
  requestProfileListen: (type: ProfileListenType, state: ProfileListenDeliveryState, providers: ProfileListenProvider[], track?: Track, durationSeconds?: number) => void;
  scheduleProfileListenRetry: (type: ProfileListenType, state: ProfileListenDeliveryState, providers: ProfileListenProvider[], track: Track, durationSeconds: number) => void;
  profileProviderLabel: (provider: ProfileListenProvider) => 'Last.fm' | 'ListenBrainz';
  handleFeedbackSubmit: (e?: React.FormEvent) => Promise<void>;
  handleLinkLastFm: () => Promise<void>;
  activeLineIdx: number;
  fetchFallbackSourceResults: (query: string, source: 'youtube_music' | 'soundcloud') => Promise<Track[]>;
  tryResolveFallbackSource: (requested: Track, requestId: number) => Promise<{ track: Track; streamUrl: string; } | null>;
  playTrack: (track: Track, newQueue?: Track[], queueIndexHint?: number, isSyncLoopCall?: boolean, isRetryCall?: boolean, preserveCurrentListenCycle?: boolean, playlistQueueOriginId?: string) => Promise<void>;
  pauseCurrentPlayback: () => void;
  resumeCurrentPlayback: () => void;
  togglePlayPause: () => void;
  handleMiniPointerDown: (e: React.PointerEvent<HTMLDivElement>) => void;
  handleMiniPointerMove: (e: React.PointerEvent<HTMLDivElement>) => void;
  handleMiniPointerUp: (e: React.PointerEvent<HTMLDivElement>) => void;
  handlePrev: (overrideIndex?: any) => void;
  stopPlaybackAtQueueBoundary: () => void;
  handleNext: (overrideIndex?: any) => void;
  commitTrackLiked: (track: Track, isLiked: boolean, syncToCloud: boolean) => void;
  setTrackLiked: (track: Track, isLiked: boolean) => void;
  applyRemoteTrackLiked: (track: Track, isLiked: boolean) => void;
  toggleLike: (track: Track) => void;
  seekToPosition: (seekTime: number) => void;
  applyLocalShuffleMode: (enabled: boolean) => void;
  applyLocalRepeatMode: (mode: 'none' | 'all' | 'one') => void;
  handleRemoteAuthorizationResponse: (response: Response, requestGeneration: number) => void;
  currentSpiceConnectLanDeviceState: () => SpiceConnectLanDeviceState;
  handleRemoteLanState: (peerDeviceId: string, state: SpiceConnectLanDeviceState) => void;
  reportRemoteDeviceState: () => Promise<void>;
  loadRemoteDevices: (showStatus?: boolean) => Promise<void>;
  scheduleRemoteDeviceSync: (delayMs?: number) => void;
  scheduleRemoteTargetRefresh: (delayMs?: number) => void;
  rememberRemoteCommandId: (commandId: string) => boolean;
  patchRemoteDevice: (deviceId: string, updates: Partial<RemoteDevice>) => void;
  clearPendingSpiceConnectHandoff: () => void;
  currentSpiceConnectHandoffPayload: (transferId: string) => NonNullable<RemoteCommand['payload']>;
  handleSpiceConnectHandoffReady: (command: RemoteCommand) => Promise<void>;
  handleSpiceConnectHandoffComplete: (command: RemoteCommand) => void;
  applySpiceConnectHandoffCommit: (command: RemoteCommand) => Promise<void>;
  shouldIgnoreRemoteCommand: (command: RemoteCommand, now: number) => boolean;
  recordRemoteTransportDiagnostic: (direction: SpiceConnectTransportDiagnostic['direction'], transport: SpiceConnectTransportDiagnostic['transport'], command: RemoteCommandType, peerDeviceId: string, latencyMs?: number) => void;
  applyRemoteCommand: (command: RemoteCommand, now: number, transport?: 'cloud' | 'lan') => void;
  pollRemoteCommands: () => Promise<void>;
  sendRemoteCommand: (command: RemoteCommandType, payload?: RemoteCommand['payload'], targetDeviceId?: string, quiet?: boolean) => Promise<boolean>;
  handleEmailVerificationSubmit: (e: React.FormEvent) => Promise<void>;
  resendEmailVerification: () => Promise<void>;
  createSecurePairingCode: () => Promise<PairingCodeResult>;
  cancelSecurePairingCode: (pairingId: string) => Promise<void>;
  claimSecurePairingCode: (code: string, displayName: string) => Promise<void>;
  loadSecurePairingAuthorizations: () => Promise<PairedDeviceAuthorization[]>;
  revokeSecurePairingAuthorization: (authorizationId: string) => Promise<void>;
  forgetLocalPairingCredential: () => void;
  remoteCommandPollDelayMs: () => 20000 | 8000 | 2000;
  remoteDeviceStateFingerprint: string;
  selectedRemoteDeviceUsesLan: boolean;
  remoteCommandRouteLabel: 'No receiver selected' | 'Local network direct' | 'Cloud server fallback';
  remoteCloudPathLabel: 'Last request used the Redis fast path' | 'Last request used PostgreSQL · Redis is not configured' | 'Last request used the PostgreSQL fallback' | 'Not checked yet';
  fetchSearchProviderResults: (query: string, provider: SearchProvider) => Promise<Track[]>;
  ensurePersonalizedUpNext: (track: Track) => Promise<Track[]>;
  queueSearch: (query: string, provider?: SearchProvider) => void;
  resolvePastedMediaLink: (query: string) => Promise<boolean>;
  handleSearchInput: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleSearchProviderChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
  handleTopbarSearchModeChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
  runTopbarSearch: (query: string, provider?: SearchProvider) => void;
  handleTopbarSearchSubmit: (e: React.FormEvent) => void;
  handleTopbarSearchInput: (e: React.ChangeEvent<HTMLInputElement>) => void;
  runRecentTopbarSearch: (entry: SearchCacheEntry) => void;
  openAccountFromTopbar: () => void;
  openSettingsFromTopbar: () => void;
  updateSidebarHiddenPreference: (hidden: boolean) => void;
  updateSidebarSearchPreference: (enabled: boolean) => void;
  updateSidebarProfilePreference: (enabled: boolean) => void;
  updateSidebarSettingsPreference: (enabled: boolean) => void;
  persistRecommendationPreferences: (nextValue: RecommendationPreferences) => void;
  recordTrackDiscoveryWin: (track: Track) => void;
  hideRecommendation: (track: Track) => void;
  snoozeRecommendationArtist: (track: Track) => void;
  dislikeRecommendation: (track: Track) => void;
  persistCustomPlaylists: (updated: Playlist[], syncOwnedPlaylists?: boolean) => void;
  createPlaylist: (e: React.FormEvent) => void;
  deletePlaylist: (playlistId: string) => Promise<void>;
  handleCoverUpload: (e: React.ChangeEvent<HTMLInputElement>) => void;
  savePlaylistEdits: (e: React.FormEvent) => Promise<void>;
  addTrackToPlaylist: (track: Track, playlistId: string) => Promise<boolean>;
  addRemoteTrackToPlaylist: (track: Track, playlistId: string, playlistTitle?: string) => Promise<boolean>;
  openPlaylistPicker: (track: Track) => void;
  savePlaylistPickerSelection: (playlistId: string) => Promise<void>;
  removeTrackFromPlaylist: (trackId: string, playlistId: string, position?: number) => Promise<void>;
  sharePlaylist: (playlist: Playlist) => Promise<void>;
  acceptSharedPlaylistInvite: () => Promise<void>;
  likedTracksList: Track[];
  editablePlaylists: Playlist[];
  sharedPlaylists: Playlist[];
  allEditablePlaylists: Playlist[];
  fetchUsername: (token?: string | null, profileId?: string) => Promise<void>;
  fetchPendingInvites: () => Promise<void>;
  fetchMyLikesCount: () => Promise<void>;
  openReleaseNotification: (notification: ReleaseNotification) => void;
  markAllReleaseNotificationsAsRead: () => void;
  handleAcceptInvite: (playlistId: string) => Promise<void>;
  handleRejectInvite: (playlistId: string) => Promise<void>;
  fetchPendingListenInvites: () => Promise<void>;
  fetchListenTogetherInvitesList: (sessionId: string) => Promise<void>;
  joinListenTogetherSession: (rawSessionId: string) => void;
  handleStartListenTogetherSession: () => Promise<void>;
  handleEndListenTogetherSession: () => Promise<void>;
  handleSendListenTogetherInvite: (username?: string) => Promise<void>;
  handleRespondToListenTogetherInvite: (inviteId: string, action: 'accept' | 'reject') => Promise<void>;
  handleLeaveListenTogetherSession: () => Promise<void>;
  handleEndOrLeaveListenTogether: () => void;
  handleInviteUserProfileToListenTogether: (username: string) => Promise<void>;
  resumeCurrentPlaybackRef: RefObject<() => void>;
  pauseCurrentPlaybackRef: RefObject<() => void>;
  seekToPositionRef: RefObject<(seekTime: number) => void>;
  enrichTrackSnapshotRef: RefObject<(track: TrackSnapshot) => TrackSnapshot>;
  fetchPlaylistMembers: (playlistId: string) => Promise<void>;
  inviteMember: (playlistId: string) => Promise<void>;
  removeMember: (playlistId: string, userId: string) => Promise<void>;
  refreshSharedPlaylist: (playlist: Playlist) => Promise<void>;
  createSharedPlaylist: (e: React.FormEvent) => Promise<void>;
  remoteTargetDevices: RemoteDevice[];
  selectedRemoteDevice: RemoteDevice | null;
  incomingRemoteController: RemoteDevice | null;
  isControllingRemoteReceiver: boolean;
  remoteReceiverPlaceholder: Track;
  playerTrack: Track;
  playerQueue: Track[];
  playerQueueIndex: number;
  playerIsPlaying: boolean;
  playerProgress: number;
  playerDuration: number;
  playerVolume: number;
  playerVolumeMax: 1000 | 100 | 200;
  playerShuffleEnabled: boolean;
  playerRepeatMode: 'none' | 'all' | 'one';
  playerIsPlaceholder: boolean;
  receiverLabel: string;
  receiverSelectDisabled: boolean;
  canControlSelectedRemoteReceiver: (command: RemoteCommandType, targetDevice?: RemoteDevice | null) => boolean;
  selectSpiceConnectReceiver: (deviceId: string) => void;
  patchSelectedRemoteDevice: (updates: Partial<RemoteDevice>) => void;
  handoffPlaybackToDevice: (targetDevice: RemoteDevice | null) => Promise<boolean>;
  handoffPlaybackToSelectedDevice: () => Promise<void>;
  startTrackOnActiveReceiver: (track: Track, newQueue?: Track[], playlistQueueOriginId?: string) => void;
  playOfflineLibraryEntry: (entry: DesktopOfflineLibraryEntry) => Promise<void>;
  showOfflineLibraryEntry: (entry: DesktopOfflineLibraryEntry) => Promise<void>;
  handleReceiverPrev: () => void;
  handleReceiverNext: () => void;
  toggleReceiverPlayPause: () => void;
  toggleReceiverShuffle: () => void;
  cycleReceiverRepeat: () => void;
  seekActiveReceiverTo: (seekTime: number) => void;
  handleReceiverSeek: (e: React.MouseEvent<HTMLDivElement>) => void;
  setReceiverVolume: (nextVolume: number) => void;
  adjustReceiverVolumeByWheel: (event: any) => void;
  refreshSpiceConnectReceiverList: () => void;
  receiverStatusLabel: (device: RemoteDevice | null) => string;
  forgetSpiceConnectDevice: (deviceId: string) => Promise<void>;
  getLikedTrackClickHandler: (track: Track) => () => void;
  getLikedTrackToggleHandler: (track: Track) => (event: React.MouseEvent<HTMLButtonElement>) => void;
  clearHistory: () => void;
  shufflePlaylistPlay: (playlist: Playlist) => void;
  downloadPlaylistToOfflineLibrary: (playlist: Playlist) => Promise<void>;
  cancelPlaylistDownload: () => void;
  getMaskedEmail: (email: string) => string;
  switchProfile: (profileId: string, profileOverride?: UserProfile) => void;
  createProfile: (e: React.FormEvent) => void;
  deleteProfile: (profileId: string) => void;
  handlePasscodeKey: (num: string) => void;
  clearPasscode: () => void;
  handleCancelPasscode: () => void;
  removePasscodeFromActive: () => void;
  saveProfile: (e: React.FormEvent) => Promise<void>;
  importYouTubePlaylist: () => Promise<void>;
  downloadBackupFile: () => void;
  copyBackupToClipboard: () => void;
  restoreBackupData: () => void;
  normalizedTopbarQuery: string;
  topbarRecentSuggestions: SearchCacheEntry[];
  topbarTrayResults: Track[];
  topbarSearchMode: TopbarSearchMode;
  shouldShowTopbarSearchTray: boolean;
  unreadReleaseNotifications: ReleaseNotification[];
  notificationCount: number;
  notificationCountLabel: string;
  isPlaylistOwner: boolean | '' | undefined;
  openCommandPage: (page: AppPage) => void;
  updatePlaybackProfiles: (nextState: PlaybackProfileState) => void;
  rebuildSmartQueue: () => void;
  commandPaletteCommands: CommandPaletteCommand[];
  runCommandQuickSearch: (query: string) => void;
}
